USE burger_db;

INSERT INTO burgers (name) VALUES ('MICHELANGELLO BURGER');
INSERT INTO burgers (name) VALUES ('CLAUDE MONETIZE BURGER');
INSERT INTO burgers (name, devoured) VALUES ('DONOT TRUMP BURGER', true);
INSERT INTO burgers (name, devoured) VALUES ('PABLANO PICASSO BURGER', true);
INSERT INTO burgers (name, devoured) VALUES ('LEONARDO DA VINCHEESE BURGER', true);
INSERT INTO burgers (name) VALUES ('VINCENT VAN GOTTA BURGER');
INSERT INTO burgers (name) VALUES ('ELON MUSTARD BURGER');
